seed: 42

metadata_csv: "D:/miniproject/mini_project-lfs/HAM10000_metadata.csv"
data_dir: "D:/miniproject/mini_project-lfs"

# Data
image_size: 224
train_test_split: 0.8

# Model
model_name: "vit_tiny"
num_classes: 7

#Training
batch_size: 32
num_epochs: 10
learning_rate: 0.0001
optimizer: "adam"

use_class_weights: true

use_augmentation: true

use_wandb: false
